env:
  global:
    - DJANGO_SETTINGS_MODULE=test_project.settings
  matrix:
    - DJANGO=1.7
    - DJANGO=1.8
    - DJANGO=1.9
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO=1.7
    - python: "3.3"
      env: DJANGO=1.7
    - python: "3.4"
      env: DJANGO=1.7
    - python: "3.5"
      env: DJANGO=1.7
    - python: "3.4"
      env: DJANGO=1.8
    - python: "3.5"
      env: DJANGO=1.8
  allow_failures:
    - python: "3.2"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
install:
  - pip install django==${DJANGO} Pillow psycopg2
  - pip install .
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database test_jsonate;' -U postgres
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
script: python test_project/manage.py test test_app
