
sudo: false
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
addons:
  postgresql: "10"
env:
  global:
    - DJANGO_SETTINGS_MODULE=test_project.settings
  matrix:
    - DJANGO=1.9
    - DJANGO=1.10
    - DJANGO=1.11
    - DJANGO=2.0
    - DJANGO=2.1
    - DJANGO=3.0
    - DJANGO=3.0.7
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO=2.0
    - python: "2.7"
      env: DJANGO=2.1
    - python: "2.7"
      env: DJANGO=3.0
    - python: "2.7"
      env: DJANGO=3.0.7
    - python: "3.7"
      env: DJANGO=1.9
    - python: "3.7"
      env: DJANGO=1.10
    - python: "3.7"
      env: DJANGO=1.11
    - python: "3.8"
      env: DJANGO=1.9
    - python: "3.8"
      env: DJANGO=1.10
    - python: "3.8"
      env: DJANGO=1.11
install:
  - pip install django==${DJANGO} Pillow psycopg2-binary
  - pip install .
before_script:
  - psql -c 'create database test_jsonate;' -U postgres

script: python test_project/manage.py test test_app
