env:
  global:
    - DJANGO_SETTINGS_MODULE=test_project.settings
  matrix:
    - DJANGO=1.9
    - DJANGO=1.10
    - DJANGO=1.11
install:
  - pip install django==${DJANGO} Pillow psycopg2
  - pip install .
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database test_jsonate;' -U postgres
language: python
python:
  - "2.7"
  - "3.6"
script: python test_project/manage.py test test_app
