sudo: false
dist: trusty
language: python
python:
  - "3.6"
  - "3.7"
addons:
  postgresql: "9.5"
env:
  global:
    - DJANGO_SETTINGS_MODULE=test_project.settings
  matrix:
    - DJANGO=2.0
    - DJANGO=2.1
    - DJANGO=2.2
install:
  - pip install django==${DJANGO} Pillow psycopg2
  - pip install .
before_script:
  - psql -c 'create database test_jsonate;' -U postgres

script: python test_project/manage.py test test_app
