sudo: false
dist: trusty
language: python
addons:
  postgresql: "9.5"

jobs:
  include:
    - python: "2.7"
      env: DJANGO=1.9
    - python: "2.7"
      env: DJANGO=1.10
    - python: "2.7"
      env: DJANGO=1.11
    - python: "3.6"
      env: DJANGO=2.0
    - python: "3.7"
      env: DJANGO=2.0
    - python: "3.8"
      env: DJANGO=2.0
    - python: "3.6"
      env: DJANGO=3.0
    - python: "3.7"
      env: DJANGO=3.0
    - python: "3.8"
      env: DJANGO=3.0
env:
  global:
    - DJANGO_SETTINGS_MODULE=test_project.settings
install:
  - pip install django==${DJANGO} Pillow psycopg2
  - pip install .
before_script:
  - psql -c 'create database test_jsonate;' -U postgres

script: python test_project/manage.py test test_app
