# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 14:16
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_field1', models.CharField(default=b'field1', max_length=25)),
                ('normal_field2', models.CharField(default=b'field2', max_length=25)),
                ('sensitive_field1', models.CharField(default=b'sensitive', max_length=25)),
                ('datetime_field', models.DateTimeField(default=datetime.datetime(2011, 1, 11, 11, 11, 11))),
                ('date_field', models.DateField(default=datetime.date(2011, 1, 11))),
                ('decimal_field', models.DecimalField(decimal_places=2, default=Decimal('32.25'), max_digits=10)),
                ('float_field', models.FloatField(default=32.25)),
                ('file_field', models.FileField(upload_to=b'files')),
                ('image_field', models.ImageField(upload_to=b'images')),
                ('boolean_field', models.BooleanField(default=True)),
                ('null_field', models.NullBooleanField(default=None)),
                ('foreign_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
