# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_auto_20180914_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodelwithrelation',
            name='many_to_many',
        ),
        migrations.AddField(
            model_name='mymodelwithrelation',
            name='many_to_many',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='many_to_my_model', to='test_app.MyModel'),
            preserve_default=False,
        ),
    ]
