# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 13:52
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_auto_20180914_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodelwithrelation',
            old_name='many_to_many',
            new_name='to_many',
        ),
    ]
