# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_auto_20180914_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodelwithrelation',
            name='to_many',
        ),
        migrations.AddField(
            model_name='mymodelwithrelation',
            name='to_many',
            field=models.ManyToManyField(related_name='many_to_my_model', to='test_app.MyModel'),
        ),
    ]
